In [1]:
#1.
'''Yes, there is a difference in the data type of the variables list_ and array_list.

list_ is a Python list object, while array_list is a NumPy array object.

To print the data types of both the variables, you can use the type() function:'''
import numpy as np

list_ = [ '1', '2', '3', '4', '5' ]
array_list = np.array(object = list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [2]:
#2.
'''To print the data type of each and every element of list_ and array_list, you can use a for loop to iterate over each element and then use the type() function to print its data type. Here's the code:'''
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("Data type of elements in array_list:")
for element in array_list:
    print(type(element))


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
#3.
'''Yes, there will be a difference in the data type of the elements present in list_ and array_list after the following change:
This is because we are explicitly specifying the dtype (data type) of the elements in the NumPy array as int. This will cause NumPy to try to convert the string elements of list_ to integers.'''
array_list = np.array(object = list_, dtype = int)



In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("Data type of elements in array_list:")
for element in array_list:
    print(type(element))


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [6]:
#4.
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [7]:
#5.
import numpy as np

# Create a 3x3 array of zeros
zeros_array = np.zeros((3, 3))

# Print the array
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#6.
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
